# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('member_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('member_type', models.CharField(max_length=255)),
                ('membership_fee', models.IntegerField()),
            ],
        ),
    ]
